### ISSUE TITLE
Wavelengths of Alpha Centauri

### ISSUE THREAD

**Issue by Jordan-Dennis** [ConaireD/TolimanWIP#2]
Hi all,
At the moment we are just using a uniform grid over the wavelengths of the TOLIMAN filter. I think that we can improve upon this but am yet to find a detailed example of the use of `dl.Spectrum` and `dl.Filter`. I believe that this functionality is not yet working.
Regards
Jordan.

**Comment by Jordan-Dennis** [comment]
Nevermind, it's looks like `dl.Filter` has a full implementation now. In that case where can I get a good representation of the TOLIMAN filter.

**Comment by Jordan-Dennis** [comment]
I have downloaded and setup `pysynphot` to use to generate the spectra. I think before going to the maximum level of detail I will just use a balckbody spectrum. Should we save this information as a `.csv` (see #1) or generate it at `__init__` time.

**Comment by ConaireD** [comment]
Eventually we will need to be able to model the spectra in the forwards model so it would be wise to have a function doing this and there likely isn't a need to save it as a csv as it will be changing. However, I think we shouldn't use just a blackbody now but we can use a generic spectra as the spectral lines will help the forwards model fit - maybe for now we can have a `.csv`  containing a generic spectra (from `pysynphot`) .We should include it for benchmarking / testing.

**Comment by Jordan-Dennis** [comment]
I'm not sure how we use the sidelobes to get the spectral information. It sounds like the samling needs to be very high unless we convolve an airy pattern with the spectrum (that is not a good wording). What are your thoughts on doing it this way @ConaireD?

**Comment by ConaireD** [comment]
So we won't be able to get exact spectral information from the sidelobes. We aren't sampling well enough, photon and detector noise makes deconvolution almost impossible, and aberrations change the convolving function. However there are regions of the spectrum that are less intense and we can use that to calibrate the plate scale and what not. Despite this, the spectra can give us *some* information, like overall temp and inferences about presence of sunspots etc which we can affect the astrometric signal . If we know about sunspots we can possibly reduce astrometric noise. However, this is more of a science issue and can be dealt with later. 

P.S. I (somewhat foolishly) looked into this issue a fair bit during my honours so feel free to ask questions.

**Comment by Jordan-Dennis** [comment]
There is a small problem that the data arrives in a very unfriendly shape so it reshaping it will be difficult.

**Comment by ConaireD** [comment]
Could you elaborate? Are you talking about extracting it from the image itself? If so it is a bit of a problem but not insurmountable with some math - or finding a match with a model. In my (idealised) simulations the sidelobes were aligned with the diagonal of the image so I just used `np.diag` for extracting them. I assume that we could have the telescope pointing to try and align the sidelobes as closely to the diagonal as possible

**Comment by Jordan-Dennis** [comment]
Oh the spectral data is 107998 long. This is an awkward number because it cannot be easily divided for binning. I sorted it out by adding a zero at the start and end.

**Comment by ConaireD** [comment]
Subissue: Make sure the wavelengths are sampled from within the filter range and not the entire EM spectrum

**Comment by Jordan-Dennis** [comment]
So it would appear that we have to use `os.environ` to set the `PYSYN_CDBS` environment variable so that we can use `pysynphot`.

**Comment by Jordan-Dennis** [comment]
So I have found one of the problems. In particular, the units of the wavelength were in Angstrogram.
