### ISSUE TITLE
Use `pytest-pydocstyle`.

### ISSUE THREAD

**Issue by Jordan-Dennis** [ConaireD/TolimanWIP#22]
Hi all,
This will let us automatically test that our docstrings are correctly formatted. I think that this will be useful. 
Regards
Jordan.

**Comment by ConaireD** [comment]
Sounds good

**Comment by Jordan-Dennis** [comment]
So it turns out that `pytest-pydocstyle` is just a wrapper to `pydocstyle` like `pytest-black` is a wrapper to `black`. I think that we keep these separate from the tests.

**Comment by Jordan-Dennis** [comment]
You can specify the docstring convention that you are using like `pydocstyle --convention=numpy`. I alo discovered a nice little hack for the number of problems using `pydocstyle | wl -l` however you must divide by two.
