### ISSUE TITLE
Implement `CONTRIBUTING.md`.

### ISSUE THREAD

**Issue by Jordan-Dennis** [ConaireD/TolimanWIP#31]
Hi all.
This is a personal reminder to set up the `CONTRIBUTING.md` file. This will need to be rather detailed since I am not using the standard setup for development. It will need to explain the use of `poetry` and `black` (see issues #20 and #14) respectively.
Regards
Jordan.

**Comment by ConaireD** [comment]
Will get to this (and everything else) tomorrow

**Comment by Jordan-Dennis** [comment]
Despite the fact I hated it in `dLux`, I am considering doing the `from packge import ...` convention. This is because I discovered the `from package import ()` multiline version which is very similar to imports in `go` and I really like. This comment is not final and I may just leave it flexible.

**Comment by ConaireD** [comment]
I personally like the `from x import y` convention. It seems more accessible.

**Comment by Jordan-Dennis** [comment]
OK sounds good :+1:. However, there are a few nuainces when it comes to submodules. Is it `from jax import numpy` or `from jax.numpy import arange, ...`.?
