### ISSUE TITLE
Find/Make Theme.

### ISSUE THREAD

**Issue by Jordan-Dennis** [ConaireD/TolimanWIP#35]
Hi all,
This is low priority but we need a theme for the docs. I'm not the biggest fan of `material` although it seems to be a popular choice. I was thinking of attempting to make a theme since there are not that many out there.
Whatr are your thoughts?
Jordan.

**Comment by ConaireD** [comment]
I am indifferent to theme use - choose which you think is best :)

**Comment by Jordan-Dennis** [comment]
What I was looking for was the `extra_css` option which will allow me to customise the colors. I do not mind so much about the remaining structure and will just use a default theme (probably `readthedocs.io`).

**Comment by Jordan-Dennis** [comment]
`mkdocs-material` provides options to customise the appearance in a fair amount of detail so the `extra.css` may not be needed.

**Comment by Jordan-Dennis** [comment]
The options are very limited and you have to use `docs/stylesheets/extra.css` anyway if you want more detail. I am going to try this.

**Comment by Jordan-Dennis** [comment]
[This](https://developer.mozilla.org/en-US/docs/Learn/CSS/Styling_text/Fundamentals) is a great guide to `css`. I shouldn't spend too much time here though.

**Comment by Jordan-Dennis** [comment]
I have implemented a simple theme in `css`, but I think that it will need to be improved as I learn more and complexity is added.
