### ISSUE TITLE
Implement `LICENSE.md`.

### ISSUE THREAD

**Issue by Jordan-Dennis** [ConaireD/TolimanWIP#37]
Hi all,
We need a license for the project. I was just going to download a default one like MIT or FreeBSD or something. @ConaireD is there a license that you prefer?
Regards
Jordan.

**Comment by ConaireD** [comment]
I have no preference (and no knowledge of) licenses. Might be something to ask Peter/Ben about - they would have thoughts about it. What does dLux use? That might be a good one

**Comment by Jordan-Dennis** [comment]
Using MIT license for now.
