### ISSUE TITLE
Error Handling

### ISSUE THREAD

**Issue by Jordan-Dennis** [ConaireD/TolimanWIP#4]
Hi all,
This is the old argument about saving the error messages as constants or not. I am in two minds about this and thinks that it makes sense in this context.
Regards
Jordan.

**Comment by Jordan-Dennis** [comment]
Perhaps it would make the most sense to start defining custom errors if there are scenarios where things are repeated. Either way I think that it is worth having an `errors.py` or `exceptions.py` file so that only the physics is in the `toliman.py` file.

**Comment by Jordan-Dennis** [comment]
I should make sure that I am been selective in the **type** of error that I use. For example, `TypeError` instead of `ValueError` when the wrong argument is provided to insert.

**Comment by ConaireD** [comment]
I admittedly am not a programmer at heart and I am mostly self taught. Do whatever you think is best / the current zeitgeist. My amateur solution would just be having handtyped print statements lol.

**Comment by Jordan-Dennis** [comment]
I think I will backflip on my current approach. Where I am re-using an error message I will create a custom exception class, otherwise I will just type the error messages in place.

**Comment by ConaireD** [comment]
Sounds good - that is normally how I handle it

**Comment by Jordan-Dennis** [comment]
This was fixed in #51.
