### ISSUE TITLE
User Defined Layers

### ISSUE THREAD

**Issue by Jordan-Dennis** [ConaireD/TolimanWIP#5]
Hi all,
We need to decide how the user can interact with the model to add and remove layers. It seems silly to me to have them provided the layers themselves but having arguments for every layer does not seem ideal either. I am going to provide a boolean interface for the default layers and then an interactive  and  method so that layers can be taken in and out of the model.
What are your thoughts?
Regards
Jordan.

**Comment by benjaminpope** [comment]
If an optical system is normally instantiated from a list of layers, how hard is it to return the list of layers and modify them as necessary?

**Comment by Jordan-Dennis** [comment]
That works. I'm a little unsure of what you mean though. The user will be able to use the `Zodiax` functionality to `.get(layer)` and `.set(layer)`, so in that regard it should be fine. I was referring to not wanting to instantiate the model with the surface roughness of the secondary mirror.

**Comment by Jordan-Dennis** [comment]
The discussion of this has moved into #6 so I am closing this issue as a duplicate.
